name: test

on:
  push:
  pull_request:
    branches: [ main ]
    paths:
    - '**.cs'
    - '**.csproj'

env:
  DOTNET_VERSION: '5.0.301' # The .NET SDK version to use

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
    - uses: dn-palmer/BigBrotherRedux@main
    - name: Test
      uses: dn-palmer/BigBrotherRedux@main
      with:
          script: BigBrotherRedux/TestingProject/TestubgProject/TestingProject.csproj