name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore https://github.com/dn-palmer/BigBrotherRedux/BigBrotherRedux/BigBrotherRedux/BBDisplay/BBDisplay/BBDisplay/BBDisplay.csproj
    - name: Build
      run: dotnet build https://github.com/dn-palmer/BigBrotherRedux/BigBrotherRedux/BigBrotherRedux/BBDisplay/BBDisplay/BBDisplay/BBDisplay.csproj --no-restore
    - name: Test
      run: dotnet test https://github.com/dn-palmer/BigBrotherRedux/BigBrotherRedux/BigBrotherRedux/TestingProject/TestingProject/TestingProject/TestingProject.csproj --no-build --verbosity normal
